backend:
  name: github
  repo: mmuflih55/blog

media_folder: content/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: tags, label: Tags, widget: list,  default: ['tech','info'] }
      - { name: thumbnail, label: Thumbnail, widget: file }
      - { name: type, default: 'blog',label: Type, widget: select, options: ['blog', 'featured'] }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
